---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20997.
--- DateTime: 2026/5/26 14:20
---
local EnemyData = {
    speed = 4,
    maxHP = 80,
    attackPower = 15,
    detectRange = 8,
    attackRange = 2,
    chaseRange = 15,
    patrolRadius = 5,
}
return EnemyData;