---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20997.
--- DateTime: 2026/5/26 14:28
---

local ComboData = {
    [0] = {
        hitboxCenter = {x = 0.0, y = 1.1, z = 0.8},
        hitboxSize = {x = 0.3, y = 0.7, z = 1.5},
        activeDuration = 0.4,
        damage = 15
    },
    [1] = {
        hitboxCenter = {x = 0.0, y = 1.3, z = 0.6},
        hitboxSize = {x = 0.3, y = 0.9, z = 1.2},
        activeDuration = 0.35,
        damage = 18
    },
    [2] = {
        hitboxCenter = {x = 0.1, y = 0.6, z = 1.2},
        hitboxSize = {x = 0.6, y = 0.5, z = 1.0},
        activeDuration = 0.35,
        damage = 12
    },
    [3] = {
        hitboxCenter = {x = 0.0, y = 0.8, z = 1.2},
        hitboxSize = {x = 0.8, y = 0.6, z = 1.0},
        activeDuration = 0.5,
        damage = 16
    },
    [4] = {
        hitboxCenter = {x = 0.0, y = 1.0, z = 1.0},
        hitboxSize = {x = 0.5, y = 1.0, z = 2.0},
        activeDuration = 0.6,
        damage = 20
    },
}

return ComboData;